apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: src-teste
  labels:
    strimzi.io/cluster: vibra
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    min.insync.replicas: 3
