apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: airbyte
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/luisaladeira/data_engineer.git"
    path: repository/helm-charts/airbyte/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingestion-batch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
